---
author: "Leo Ohyama"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Education

**2019-Current** University of Florida, PhD

**2016-2019** University of Central Florida, MS Biology

**2012-2016** Boise State University, BS Biology

# Publications

**5** \*Hornfeldt, J., **L. Ohyama**, A. Lucky. 2020. Using Behavioral Experimentation to Understand the Social Structure of the Little Fire Ant (Wasmannia auropunctata) in Florida. UF Journal of Undergraduate Research 22.
*Undergraduate student mentee

**4** Lucky, A., R. Atchison., **L. Ohyama.**, Y.M. Zhang., J. Williams., J. Pinkey., K. Clancy., A. Nielsen., C.A. Lippi. 2020. Myrmecology, Gender, and Geography: Changing demographics of a research community over thirty years. Myrmecological News 39:187-199.
[\*Awarded best paper by Myrmecological News for 2020](https://blog.myrmecologicalnews.org/2021/02/04/best-paper-award-2020/)

**3** **Ohyama, L.**, J.R. King., B.M. Gochnour. 2020. Changes in an invaded ant community in Florida (Hymenoptera: Formicidae) over 25 years. The Florida Entomologist 103(2):180-190.

**2** **Ohyama, L.**, J.R. King., D.G. Jenkins. 2020. Are tiny subterranean ants top predators in ant communities?. Ecology 101(8): e03084
[\*Covered in Science Magazine](https://www.sciencemag.org/news/2020/05/thief-ants-steal-and-eat-young-other-ants-decimating-their-populations)

**1** **Ohyama, L.**, J.R. King., D.G. Jenkins. 2018. Diversity and distribution of Solenopsis (Hymenoptera: Formicidae) thief ants belowground. Myrmecological News 27:47-57.
[\*Covered by Myrmecological News](https://blog.myrmecologicalnews.org/2018/07/12/diversity-and-distribution-of-solenopsis-thief-ants-belowground/)

# Funding and Awards
2020
Entomological Society of America National Meeting, 10-minute paper competition in climate change & biogeography, 1st place ($75)

2020-21 
University of Florida Biodiversity Institute Fellowship ($22,000/9 months)

2019-22	
University of Florida Graduate School Funding Award ($31,000/year for 4 years)

2019	University of Central Florida Student Government Association Special Scholarship ($500)

2018	University of Central Florida Student Government Association Research Travel Award ($250)

2018	University of Central Florida Student Government Association International Graduate Scholarship ($500)

2018	University of Central Florida Research Foundation Grant
PI: Joshua R. King, Co-PI: Leo Ohyama -- $1,000 dollars
Project title: Floridian thief ant (Hymenoptera: Formicidae: Solenopsis) species delimitation in a phylogenetic framework

2018	Entomological Society of America Southeastern Branch Meeting Masters Student Poster Competition 2nd place ($100)

2017	Arnold Haverlee Exploration Endowed Award ($1000)

2017	University of Central Florida Student Government Association Special Scholarship ($500)

2017	University of Central Florida Biology Department Pre-Proposal Award ($100)

2016	Bishop Barnwell Student Leadership award ($400)

2012-16	Boise State University Gem Scholarship ($36,000)

# Presentations

Hornfledt, J.A., **Ohyama, L**, A. Lucky. (2020, November) The little fire ant: Using behavioral experimentation to understand invasive ant social structure. Talk presented at the Entomological Society of America Annual Meeting, Virtual

Lucky, A., R. Atchison., Y.M. Zhang., **Ohyama, L**, J. Williams., J. Pinkey., K. Clancy., A. Nielsen., C.A. Lippi. (2020, November) Myrmecology, Gender, and Geography: Changing demographics of a research community over thirty years. Talk presented at the Entomological Society of America Annual Meeting, Virtual

**Ohyama, L**., R.D. Holt, T.J., Matthews., A. Lucky. (2020, November) The species-area relationship in ant ecology. Talk presented at the Entomological Society of America Annual Meeting, Virtual 

Lucky, A., R. Atchison., Y.M. Zhang., **Ohyama, L**, J. Williams., J. Pinkey., K. Clancy., A. Nielsen., C.A. Lippi. (2020, March) Myrmecology, Gender, and Geography: Changing demographics of a research community over thirty years. Talk given at the Social Insects in the East Region Conference, Brooklyn, New York **Cancelled due to coronavirus pandemic

Bogota, J.D., **Ohyama, L**, A. Acosta-Santos, E. Agudelo-Cordoba. (2019, July) Using remote sensing to evaluate surrounding land use and cover on freshwater fish assemblage structure and water quality from the Upper Amazon Basin, Columbia. Poster presented at the XV Columbian Congress of Ichthyology and VI Meeting of Ichthyologists Suramericanos, Medellin, Colombia

**Ohyama, L**, J.R. King, B.M., Gochnour. (2018, March) Changes in an invaded Florida ant community over 25 years. Poster presented at the University of Central Florida Graduate Research Fair, Orlando, Florida

**Ohyama, L** (2018, December) Invited speaker, On the ecology of Solenopsis thief ants and the integration of GIS technology in assessing diversity, Talk given at the University of Florida Department of Entomology and Nematology, Gainesville, Florida

**Ohyama, L**, J.R. King, D.G. Jenkins (2018, August) Diversity and distribution of Solenopsis (Hymenoptera: Formicidae) thief ants belowground. Talk given at the Ecological Society of America national meeting, New Orleans, Louisiana

**Ohyama, L**, J.R. King. (2018, March) Diversity and distribution of Solenopsis (Hymenoptera: Formicidae) thief ants belowground. Poster presented at the Entomological Society of America Southeastern Branch Meeting, Orlando, Florida


