<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Leo_Ohyama" />


<title>Data Exploration Script</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/darkly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>





<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Ohyama</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="CV.html">CV</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Research
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="macroecology.html">Macroecology</a>
    </li>
    <li>
      <a href="SAR.html">Island Biogeography</a>
    </li>
    <li>
      <a href="thiefant.html">Community Ecology</a>
    </li>
    <li>
      <a href="readings-module4.html">Non-ants</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R stuff
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="NYCflights.html">Data Exploration</a>
    </li>
    <li>
      <a href="maps.html">Global Maps</a>
    </li>
    <li>
      <a href="subsampling.html">Subsampling at the global scale</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Data Exploration Script</h1>
<h4 class="author">Leo_Ohyama</h4>
<h4 class="date">2/21/2021</h4>

</div>


<pre class="r"><code>#packages needed to run this
library(tidyverse) 
library(agridat)
library(corrplot) #new package
library(EnvStats) #new package
library(nycflights13) #new package
library(GGally) #new package</code></pre>
<p>This script comes from my lecture on data exploration in R. I try and use open-source data whenever possible. The highlights of this script is to:</p>
<ol style="list-style-type: decimal">
<li><p>Provide the user with an understanding of how to assess their dtata structure (e.g. how many rows, how many columns)</p></li>
<li><p>Compare central tendency measures across different types of data distribution</p></li>
<li><p>Utilize different packages to quickly assess correlaitons between numeric or continuous variables within a data set</p></li>
<li><p>Utilize the tidyverse, to rapidly explore data and patterns with a relatively large dataset</p></li>
</ol>
<div id="tomato-yields-assessing-and-quickly-examining-data-structure" class="section level1">
<h1>Tomato yields: Assessing and quickly examining data structure</h1>
<p>Here we use a dataset on tomota yields from different environments and different genotypes from the package ‘agridat’ . Setup the yield dataset:</p>
<pre class="r"><code>data(&quot;ortiz.tomato.yield&quot;)
data(&quot;ortiz.tomato.covs&quot;)
yield &lt;- as_tibble(ortiz.tomato.yield)
covs &lt;- as_tibble(ortiz.tomato.covs)
tomato &lt;- full_join(yield,covs, by=&#39;env&#39;) %&gt;% filter(Driv==0)</code></pre>
<p>Reviewing ways to look at structure in the datset:</p>
<pre class="r"><code>str(tomato)</code></pre>
<pre><code>## tibble [120 × 22] (S3: tbl_df/tbl/data.frame)
##  $ env   : Factor w/ 18 levels &quot;E04&quot;,&quot;E05&quot;,&quot;E06&quot;,..: 4 8 9 11 12 13 14 16 4 8 ...
##  $ gen   : Factor w/ 15 levels &quot;H11&quot;,&quot;H14&quot;,&quot;H5&quot;,..: 8 8 8 8 8 8 8 8 13 13 ...
##  $ yield : num [1:120] 36.4 8.7 18.7 82.5 93.9 15 95.8 3.1 25.6 7.1 ...
##  $ weight: num [1:120] 96.6 79.2 83.3 113.5 93.9 ...
##  $ Day   : int [1:120] 1111 1043 605 970 674 566 765 1463 1111 1043 ...
##  $ Dha   : int [1:120] 109 91 104 102 133 111 105 91 109 91 ...
##  $ Driv  : int [1:120] 0 0 0 0 0 0 0 0 0 0 ...
##  $ ExK   : int [1:120] 131 180 102 100 131 80 25 100 131 180 ...
##  $ ExN   : int [1:120] 151 180 165 180 200 133 162 100 151 180 ...
##  $ ExP   : int [1:120] 33 180 102 100 300 127 45 100 33 180 ...
##  $ Irr   : int [1:120] 0 1 1 1 1 1 1 0 0 1 ...
##  $ K     : num [1:120] 5 1 0.8 0.1 0 2 3 15 5 1 ...
##  $ Lat   : num [1:120] 13.4 18.2 18.3 12 33.3 36.3 33.2 2 13.4 18.2 ...
##  $ Long  : num [1:120] 89.2 70.4 69.2 76.6 70.4 70.4 71.1 48 89.2 70.4 ...
##  $ MeT   : int [1:120] 25 28 21 20 19 19 19 23 25 28 ...
##  $ MnT   : int [1:120] 15 19 7 11 13 4 7 22 15 19 ...
##  $ MxT   : int [1:120] 34 36 30 30 34 36 34 33 34 36 ...
##  $ OM    : num [1:120] 3 2 5 2 2 3 2 1 3 2 ...
##  $ P     : int [1:120] 76 19 22 53 8 51 30 5 76 19 ...
##  $ pH    : int [1:120] 6 8 6 7 8 6 7 4 6 8 ...
##  $ Prec  : int [1:120] 580 377 314 228 228 19 11 27 580 377 ...
##  $ Trim  : int [1:120] 0 0 0 0 0 0 0 0 0 0 ...</code></pre>
<pre class="r"><code>summary(tomato)</code></pre>
<pre><code>##       env          gen         yield             weight           Day        
##  E07    :15   H11    : 8   Min.   :  0.300   Min.   : 26.9   Min.   : 566.0  
##  E20    :15   H14    : 8   1st Qu.:  8.775   1st Qu.: 74.9   1st Qu.: 656.8  
##  E21    :15   H5     : 8   Median : 20.100   Median : 97.8   Median : 867.5  
##  E40    :15   H6     : 8   Mean   : 38.633   Mean   :101.6   Mean   : 899.6  
##  E41    :15   H7     : 8   3rd Qu.: 74.175   3rd Qu.:128.8   3rd Qu.:1060.0  
##  E42    :15   H8     : 8   Max.   :138.800   Max.   :182.3   Max.   :1463.0  
##  (Other):30   (Other):72                                                     
##       Dha              Driv        ExK             ExN             ExP        
##  Min.   : 91.00   Min.   :0   Min.   : 25.0   Min.   :100.0   Min.   : 33.00  
##  1st Qu.: 99.25   1st Qu.:0   1st Qu.: 95.0   1st Qu.:146.5   1st Qu.: 86.25  
##  Median :104.50   Median :0   Median :101.0   Median :163.5   Median :101.00  
##  Mean   :105.75   Mean   :0   Mean   :106.1   Mean   :158.9   Mean   :123.38  
##  3rd Qu.:109.50   3rd Qu.:0   3rd Qu.:131.0   3rd Qu.:180.0   3rd Qu.:140.25  
##  Max.   :133.00   Max.   :0   Max.   :180.0   Max.   :200.0   Max.   :300.00  
##                                                                               
##       Irr             K               Lat             Long      
##  Min.   :0.00   Min.   : 0.000   Min.   : 2.00   Min.   :48.00  
##  1st Qu.:0.75   1st Qu.: 0.625   1st Qu.:13.05   1st Qu.:70.10  
##  Median :1.00   Median : 1.500   Median :18.25   Median :70.40  
##  Mean   :0.75   Mean   : 3.362   Mean   :20.84   Mean   :70.66  
##  3rd Qu.:1.00   3rd Qu.: 3.500   3rd Qu.:33.23   3rd Qu.:72.47  
##  Max.   :1.00   Max.   :15.000   Max.   :36.30   Max.   :89.20  
##                                                                 
##       MeT             MnT             MxT              OM            P        
##  Min.   :19.00   Min.   : 4.00   Min.   :30.00   Min.   :1.0   Min.   : 5.00  
##  1st Qu.:19.00   1st Qu.: 7.00   1st Qu.:32.25   1st Qu.:2.0   1st Qu.:16.25  
##  Median :20.50   Median :12.00   Median :34.00   Median :2.0   Median :26.00  
##  Mean   :21.75   Mean   :12.25   Mean   :33.38   Mean   :2.5   Mean   :33.00  
##  3rd Qu.:23.50   3rd Qu.:16.00   3rd Qu.:34.50   3rd Qu.:3.0   3rd Qu.:51.50  
##  Max.   :28.00   Max.   :22.00   Max.   :36.00   Max.   :5.0   Max.   :76.00  
##                                                                               
##        pH            Prec            Trim  
##  Min.   :4.00   Min.   : 11.0   Min.   :0  
##  1st Qu.:6.00   1st Qu.: 25.0   1st Qu.:0  
##  Median :6.50   Median :228.0   Median :0  
##  Mean   :6.50   Mean   :223.0   Mean   :0  
##  3rd Qu.:7.25   3rd Qu.:329.8   3rd Qu.:0  
##  Max.   :8.00   Max.   :580.0   Max.   :0  
## </code></pre>
</div>
<div id="measure-of-central-tendency-measures" class="section level1">
<h1>Measure of central tendency measures</h1>
<p>Here we measure and compare how central tendency measures fluctuate between different distributions. We first caclulate the mean, and median. Note we use na.rm=T because we have NAs in the data. When we use this argument R will remove NAs when calculating your metrics</p>
<pre class="r"><code>#calculate the mean and median for weight
mean_weight&lt;-mean(tomato$weight, na.rm = T)
median_weight&lt;-median(tomato$weight,na.rm = T)</code></pre>
<p>Get a histogram of the distribution of weight:</p>
<pre class="r"><code>ggplot(tomato) + geom_histogram(aes(x = weight), color = &quot;white&quot;) + theme_classic()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Looks relatively normally distributed but let’s re-plot but with the mean and the median as vertical lines mean will be colored in blue, median in orange:</p>
<pre class="r"><code>ggplot(tomato) +
  geom_histogram(aes(x = weight), color = &quot;white&quot;) +
  geom_vline(aes(xintercept= mean_weight), color = &quot;blue&quot;, size = 2)+
  geom_vline(aes(xintercept= median_weight), color = &quot;orange&quot;, size = 2) +
  theme_classic()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>They’re right on top of each other which is characteristic of a normally distributed variable</p>
<pre class="r"><code>#calculate the mean and median for yield
mean_yield&lt;-mean(tomato$yield, na.rm = T)
median_yield&lt;-median(tomato$yield,na.rm = T)
mean_yield</code></pre>
<pre><code>## [1] 38.6325</code></pre>
<pre class="r"><code>median_yield</code></pre>
<pre><code>## [1] 20.1</code></pre>
<p>Get a histogram of the distribution of yield:</p>
<pre class="r"><code>ggplot(tomato) + 
  geom_histogram(aes(x = yield), color = &quot;white&quot;) +
  theme_classic()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Looks very right (positive) skewed</p>
<p>Again re-plot with the mean and the median:</p>
<pre class="r"><code>ggplot(tomato) +
  geom_histogram(aes(x = yield), color = &quot;white&quot;) +
  geom_vline(aes(xintercept= mean_yield), color = &quot;blue&quot;, size = 2)+
  geom_vline(aes(xintercept= median_yield), color = &quot;orange&quot;, size = 2) +
  theme_classic()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>This time there is a spread. Median is less than the mean. The median is actually more closer to the mode of the yield (taller bars) than the mean.</p>
</div>
<div id="correlations" class="section level1">
<h1>Correlations</h1>
<p>We can first use the GGally package. The ggpairs() code provides us with scatter plots that plot variables against one another in a pairwise fashion. We also see the distribution of the data and the correlation coefficients between a pair of variables</p>
<pre class="r"><code>ggpairs(tomato %&gt;% dplyr::select(pH, P, K, weight, yield)) #select only 5 variables #interest</code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Let’s use the corrplot package to identify which variables are correlated with one another. First we need to make a correlation matrix of the data. Here we calculate a correlation matrix using a pearson’s correlation coefficicent method. Keep in mind that the pearson’s method often assumes nromality between variables which we did not check. Other methods such as spearman’s correlation coefficent can be used for non-normal data.</p>
<pre class="r"><code>cor_tomatos&lt;-cor(tomato %&gt;% select(-env,-gen) %&gt;% na.omit(), method = c(&quot;pearson&quot;))</code></pre>
<pre><code>## Warning in cor(tomato %&gt;% select(-env, -gen) %&gt;% na.omit(), method =
## c(&quot;pearson&quot;)): the standard deviation is zero</code></pre>
<p>Let’s visualize this matrix better with the corrplot package. This line of code will generate a plot showing the relationships between all variables in pairwise manner using the correlation matrix we made previously. The colors represent the value of the correlation coefficent. Blues indicate positive correlation while reds refelct negative correlations. The size of the circles reflect the correlation coefficient (e.g, bigger circles represent larger correlation coefficeint values).</p>
<pre class="r"><code>corrplot(cor_tomatos, method = &quot;circle&quot;, type = &quot;upper&quot;)</code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="if-you-want-both-the-circles-and-the-correlation-coefficients-you-can-run-this-line" class="section level1">
<h1>If you want both the circles and the correlation coefficients you can run this line:</h1>
<pre class="r"><code>corrplot.mixed(cor_tomatos)</code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="data-exploration-approaches-with-the-tidyverse" class="section level1">
<h1>Data exploration approaches with the tidyverse</h1>
<p>Here we use a dataset named ‘flights’ from the nycflights12 package. This is data showing every flight to come out of three New York Airports in the year 2013 (domestic only). It comes with the main data named ‘flights’ but also comes with extra datasets (or metadata files) names ‘airlines’ and ‘airports’. ‘Airlines’ provides the airline name for each carrier code (e.g. UA is United Airlines) ’Airports provides an airport name for each destination code (MCO is Orlando)</p>
<p>Let’s load up the flights dataset:</p>
<pre class="r"><code>data(&quot;flights&quot;)</code></pre>
<p>We see that this dataset is rather large w/ 336,776 rows</p>
<pre class="r"><code>str(flights)</code></pre>
<pre><code>## tibble [336,776 × 19] (S3: tbl_df/tbl/data.frame)
##  $ year          : int [1:336776] 2013 2013 2013 2013 2013 2013 2013 2013 2013 2013 ...
##  $ month         : int [1:336776] 1 1 1 1 1 1 1 1 1 1 ...
##  $ day           : int [1:336776] 1 1 1 1 1 1 1 1 1 1 ...
##  $ dep_time      : int [1:336776] 517 533 542 544 554 554 555 557 557 558 ...
##  $ sched_dep_time: int [1:336776] 515 529 540 545 600 558 600 600 600 600 ...
##  $ dep_delay     : num [1:336776] 2 4 2 -1 -6 -4 -5 -3 -3 -2 ...
##  $ arr_time      : int [1:336776] 830 850 923 1004 812 740 913 709 838 753 ...
##  $ sched_arr_time: int [1:336776] 819 830 850 1022 837 728 854 723 846 745 ...
##  $ arr_delay     : num [1:336776] 11 20 33 -18 -25 12 19 -14 -8 8 ...
##  $ carrier       : chr [1:336776] &quot;UA&quot; &quot;UA&quot; &quot;AA&quot; &quot;B6&quot; ...
##  $ flight        : int [1:336776] 1545 1714 1141 725 461 1696 507 5708 79 301 ...
##  $ tailnum       : chr [1:336776] &quot;N14228&quot; &quot;N24211&quot; &quot;N619AA&quot; &quot;N804JB&quot; ...
##  $ origin        : chr [1:336776] &quot;EWR&quot; &quot;LGA&quot; &quot;JFK&quot; &quot;JFK&quot; ...
##  $ dest          : chr [1:336776] &quot;IAH&quot; &quot;IAH&quot; &quot;MIA&quot; &quot;BQN&quot; ...
##  $ air_time      : num [1:336776] 227 227 160 183 116 150 158 53 140 138 ...
##  $ distance      : num [1:336776] 1400 1416 1089 1576 762 ...
##  $ hour          : num [1:336776] 5 5 5 5 6 5 6 6 6 6 ...
##  $ minute        : num [1:336776] 15 29 40 45 0 58 0 0 0 0 ...
##  $ time_hour     : POSIXct[1:336776], format: &quot;2013-01-01 05:00:00&quot; &quot;2013-01-01 05:00:00&quot; ...</code></pre>
<p>Here are the carrier codes and the corresponding airline names:</p>
<pre class="r"><code>data(&quot;airlines&quot;)
airlines</code></pre>
<pre><code>## # A tibble: 16 x 2
##    carrier name                       
##    &lt;chr&gt;   &lt;chr&gt;                      
##  1 9E      Endeavor Air Inc.          
##  2 AA      American Airlines Inc.     
##  3 AS      Alaska Airlines Inc.       
##  4 B6      JetBlue Airways            
##  5 DL      Delta Air Lines Inc.       
##  6 EV      ExpressJet Airlines Inc.   
##  7 F9      Frontier Airlines Inc.     
##  8 FL      AirTran Airways Corporation
##  9 HA      Hawaiian Airlines Inc.     
## 10 MQ      Envoy Air                  
## 11 OO      SkyWest Airlines Inc.      
## 12 UA      United Air Lines Inc.      
## 13 US      US Airways Inc.            
## 14 VX      Virgin America             
## 15 WN      Southwest Airlines Co.     
## 16 YV      Mesa Airlines Inc.</code></pre>
<p>The seed allows us to get reproducible results and here’s how we set it:</p>
<pre class="r"><code>set.seed(1234) </code></pre>
<p>Let’s grab a random subsample to make it easier to work with the sample_n function allows us to randomly sample rows from a dataset. Here we sample just 20,000 rows. Your computer will thank you later when you are plotting these data</p>
<pre class="r"><code>ny_flights&lt;-sample_n(flights, 20000)
ny_flights</code></pre>
<pre><code>## # A tibble: 20,000 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
##  1  2013     6    17     1033           1040        -7     1246           1309
##  2  2013    12    26     1343           1329        14     1658           1624
##  3  2013     8    26     1258           1218        40     1510           1516
##  4  2013     8    17     1558           1600        -2     1835           1849
##  5  2013     2    17       NA           1500        NA       NA           1653
##  6  2013     6    30      905            900         5     1200           1206
##  7  2013     9    15     1017           1025        -8     1245           1325
##  8  2013     5     7     1623           1627        -4     1819           1818
##  9  2013     3    14      703            645        18      854            846
## 10  2013     9     4      739            740        -1     1030           1055
## # … with 19,990 more rows, and 11 more variables: arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p>Let’s see how many flights total came out of each airport during the year. We can use the n() function to count up the total number of observations. In this case we are counting the total number of observations in each group (origin/airport)/</p>
<pre class="r"><code>ny_flights %&gt;% 
  group_by(origin) %&gt;%
  summarise(total_flights = n())</code></pre>
<pre><code>## # A tibble: 3 x 2
##   origin total_flights
## * &lt;chr&gt;          &lt;int&gt;
## 1 EWR             7200
## 2 JFK             6597
## 3 LGA             6203</code></pre>
<p>We see that EWR (Newark Liberty Airport has the most outgoing flights). But more importantly it tells us that the flights are more or less evenly distributed between the three airports. No single airport is taking up most of the data.</p>
<p>Let’s see which carriers from which airports had the most amount of flight delays? Note: I filter out negative departure delay times because those represent planes that departed ahead of schedule. Note: I use the na.rm =T argument here because there are NAs in the datset for dep_delay</p>
<pre class="r"><code>delayed_planes&lt;-ny_flights %&gt;% 
  filter(dep_delay &gt; 0) %&gt;%
  group_by(origin, carrier) %&gt;%
  summarise(total_delay = sum(dep_delay, na.rm = T)) %&gt;%
  arrange(desc(total_delay))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;origin&#39;. You can override using the `.groups` argument.</code></pre>
<pre class="r"><code>delayed_planes</code></pre>
<pre><code>## # A tibble: 33 x 3
## # Groups:   origin [3]
##    origin carrier total_delay
##    &lt;chr&gt;  &lt;chr&gt;         &lt;dbl&gt;
##  1 EWR    EV            60336
##  2 EWR    UA            41592
##  3 JFK    B6            36854
##  4 JFK    9E            18152
##  5 LGA    DL            17338
##  6 JFK    DL            12947
##  7 LGA    MQ            11738
##  8 LGA    EV            10508
##  9 JFK    AA            10472
## 10 LGA    AA             8977
## # … with 23 more rows</code></pre>
<pre class="r"><code>airlines</code></pre>
<pre><code>## # A tibble: 16 x 2
##    carrier name                       
##    &lt;chr&gt;   &lt;chr&gt;                      
##  1 9E      Endeavor Air Inc.          
##  2 AA      American Airlines Inc.     
##  3 AS      Alaska Airlines Inc.       
##  4 B6      JetBlue Airways            
##  5 DL      Delta Air Lines Inc.       
##  6 EV      ExpressJet Airlines Inc.   
##  7 F9      Frontier Airlines Inc.     
##  8 FL      AirTran Airways Corporation
##  9 HA      Hawaiian Airlines Inc.     
## 10 MQ      Envoy Air                  
## 11 OO      SkyWest Airlines Inc.      
## 12 UA      United Air Lines Inc.      
## 13 US      US Airways Inc.            
## 14 VX      Virgin America             
## 15 WN      Southwest Airlines Co.     
## 16 YV      Mesa Airlines Inc.</code></pre>
<p>Looks like carrier EV (ExpressJet Airlines Inc.) was delayed the most coming out of EWR (Newark Liberty) followed by UA (United Airlines). EV had a total of 60336 delayed minutes which translate to roughly a total delay of 41.9 hours! Keep in mind we are only using 20000 rows here (6 % of the data)!</p>
<p>Let’s plot some of this data. Here we use the geom_tile() in ggplot which is useful for plotting categorical variables on both axes:</p>
<pre class="r"><code>ggplot(delayed_planes) +
  geom_tile(aes(x = origin, y = carrier, fill = total_delay), alpha = 0.9,color = &quot;Grey&quot;) +
  theme_classic() </code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Let’s finally explore trends over time. More specifically, are there more departure delays in certain months? Let’s focus of United Airlines coming out of Newark because we know it’s one of the more busier airports from our previous code</p>
<pre class="r"><code>delay_months&lt;-ny_flights %&gt;%
  filter(carrier == &quot;UA&quot;, origin == &quot;EWR&quot; , dep_delay&gt;0) %&gt;%
  group_by(month) %&gt;%
  summarise(delay_min = sum(dep_delay, na.rm = T))

ggplot(data = delay_months) + 
  geom_line(aes(x = month, y = delay_min)) +
  geom_point(aes(x=month, y = delay_min), size = 4) + 
  labs(x = &quot;Month&quot;, y = &quot;Total departure delays (minutes)&quot;)</code></pre>
<p><img src="NYCflights_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Basically don’t fly on United Airlines out of Newark in July or December!</p>
<p>Final thing. What are the top 5 airlines/carrier in terms of outgoing flight volume from all the airports and where are these airlines primarily flying too? Note: Here we use two chunks of dplyr code. The first identifies the the top 5 airlines the next uses the first chunk to filter for those top 5 using the “%in%” operator</p>
<pre class="r"><code>top_airlines&lt;-ny_flights %&gt;% 
  group_by(carrier) %&gt;%
  summarise(total = n()) %&gt;%
  arrange(desc(total)) %&gt;% #not arrange(desc()) basically arranges the column (total) in descending order
  top_n(n = 5)</code></pre>
<pre><code>## Selecting by total</code></pre>
<pre class="r"><code>top_airlines # Here we see the top carriers are UA, B6, EV, DL, AA</code></pre>
<pre><code>## # A tibble: 5 x 2
##   carrier total
##   &lt;chr&gt;   &lt;int&gt;
## 1 UA       3522
## 2 B6       3286
## 3 EV       3192
## 4 DL       2856
## 5 AA       1923</code></pre>
<pre class="r"><code>ny_flights %&gt;%
  filter(carrier %in% top_airlines$carrier) %&gt;%
  group_by(carrier,dest) %&gt;%
  summarise(total= n()) %&gt;%
  arrange(desc(total))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;carrier&#39;. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 186 x 3
## # Groups:   carrier [5]
##    carrier dest  total
##    &lt;chr&gt;   &lt;chr&gt; &lt;int&gt;
##  1 DL      ATL     629
##  2 UA      IAH     446
##  3 AA      DFW     422
##  4 AA      MIA     416
##  5 B6      FLL     415
##  6 UA      ORD     399
##  7 B6      MCO     385
##  8 UA      SFO     375
##  9 UA      LAX     329
## 10 AA      ORD     328
## # … with 176 more rows</code></pre>
<p>Looks like Delta (DL) flew 629 total flights to Atlanta (ATL). Atlanta must be a very popular spot! But why?! This is where data exploration becomes limited. We have no data to support why Atlanta is popular. However thankfully we know that Hartsfield Jackson (Atlanta’s main airport) is a primary hub for Delta Airlines. That’s why the airline tries to keep all their flights moving through ATL. This showcases how powerful data exploration is but how sometimes it can leads to wrong assumptions.</p>
</div>
<div id="r-challenge-used-for-actual-lab-activity.-answers-provided" class="section level1">
<h1>R challenge used for actual lab activity. Answers provided</h1>
<div id="section" class="section level70">
<p></p>
</div>
<div id="r-challenge-data-exploration-due-xyz" class="section level4">
<h4>R CHALLENGE Data Exploration DUE XYZ</h4>
<p>#’For this challenge we will use the flights dataset</p>
<p>#‘Question 1: Two parts. First, which months had the most flights departing each of the three airports? #’ Second, show a line plot of all three airports and the number of flights departing them across #’ every month (Hint: x-axis would be months, y would be the number of flights).</p>
<p>Q1&lt;-ny_flights %&gt;% group_by(month, origin) %&gt;% summarise(total = n()) %&gt;% arrange(desc(total)) %&gt;% ungroup()</p>
<p>ggplot(Q1, aes(x = month, y = total, color = origin,group = origin)) + geom_point(aes(x = month, y = total, color = origin)) + geom_line(aes(x = month, y = total, color = origin)) + theme_bw()</p>
<p>#fancier way of doing this Q1&lt;-ny_flights %&gt;% mutate(month_name = factor(month.name[month], levels = month.name)) %&gt;% group_by(month_name, origin) %&gt;% summarise(total = n()) %&gt;% arrange(desc(total)) %&gt;% ungroup() ggplot(Q1, aes(x = month_name, y = total, color = origin,group = origin)) + geom_point(stat=‘summary’, fun.y=sum) + stat_summary(fun.y=sum, geom=“line”) + labs(x = “Months”, y = &quot; Total Flights&quot;) + theme_bw()</p>
<p>#’ Question2: Which airline/carrier flew the most miles, the most number of flights? #’ Also which carrier had the lowest miles to flights ratio? #’ (Lower miles to fligh ratio would mean an airline flew less miles per flight)</p>
<p>ny_flights %&gt;% group_by(carrier) %&gt;% summarise(total_miles = sum(distance) ,total_flight = n()) %&gt;% mutate(Ratio = total_miles/total_flight)</p>
<p>#‘Question 3:Identify the 10 most popular destinations from all three airports. #’Then filter the dataset for these 10 destinations. #’For every month, which destination received the most flights and from which airports? #’ How would you plot this?</p>
<p>top_ten&lt;-ny_flights %&gt;% group_by(dest) %&gt;% summarise(total = n()) %&gt;% arrange(desc(total)) %&gt;% top_n(n = 5) %&gt;% dplyr::select(dest)</p>
<p>where_do_I_go&lt;-ny_flights %&gt;% filter(dest %in% c(“ATL”, “BOS”, “ORD”, “LAX”, “MCO”)) %&gt;% group_by(origin,dest, month) %&gt;% summarise(total = n())</p>
<p>ggplot(where_do_I_go) + geom_point(aes(x = month, y = total, color = origin)) + geom_line(aes(x = month, y = total, color = origin)) + facet_wrap(~dest)</p>
<p>#Optional: CHALLENGE CHALLENGE #’ Which carriers fly to which of the top ten destinations at what time of the day? #’ Play around with the full dataset ‘flights’! See how much faster or slower it might take to #’ run certain plots and operators! #’ Hint: you can use the “hours” variable as time of day flights %&gt;% filter(dest %in% top_ten$dest) %&gt;% group_by(dest, carrier, hour) %&gt;% summarise(total= n()) %&gt;% ggplot(., aes(x = hour, y = dest, fill = total)) + geom_tile() + facet_wrap(~carrier) + scale_fill_viridis_c()</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
